version: '3.3'

networks:
  service_network:

volumes:
  service_data:

services:
  service:
    image: my-service-img
    networks:
      - service_network
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - service_data:/my/volume
