version: '3'

networks:
  service_network:

volumes:
  service_data:
  service_config:

services:
  service:
    image: busybox:latest
    networks:
      - service_network
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - service_data:/my/volume
      - service_config:/etc/my-service-config

  service_config:
    image: my-service-image
    networks:
      - service_network
    volumes:
      - service_config:/etc/my-service-config
